In [2]:
import torch

## Tensors
construct a randomly initialized tensor

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6708, 0.1277, 0.4941],
        [0.6428, 0.0142, 0.2180],
        [0.8763, 0.2915, 0.0949],
        [0.5114, 0.4509, 0.0380],
        [0.3757, 0.3218, 0.3037]])


Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3192,  0.2858, -0.5669],
        [-0.1954,  0.6056, -1.6588],
        [-0.4348,  0.7584, -0.7199],
        [-1.4854,  0.8495,  0.2727],
        [-0.5049, -1.6737, -0.4658]])
torch.Size([5, 3])


## Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

Addition: syntax 1

In [ ]:
y = torch.rand(5, 3)
print(x + y)

Addition: syntax 2

In [ ]:
print(torch.add(x, y))

Addition: providing an output tensor as argument

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

In-place addition

In [ ]:
# adds x to y
y.add_(x)
print(y)

<div class="alert alert-success">
Any operation that mutates a tensor in-place is post-fixed with an \_. For example: __x.copy\_(y)__, __x.t\_()__, will change __x__.
</div>

You can use standard NumPy-like indexing

In [ ]:
print(x[:, 1])

Resizing: if you want to resize/reshape a tensor, you can use __torch.view__:

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

If you have a one element tensor, use __.item()__ to get the value as a Python number

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

For more information, read the [documentation](https://pytorch.org/docs/stable/torch.html)

## Numpy bridge
Converting a Torch Tensor to a NumPy array is easy. The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

### Converting a Torch Tensor to a Numpy Array

In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1) # see how the numpy array changed both variables
print(a)
print(b)

### Converting NumPy Array to Torch Tensor
See how changing the np array changed the Torch Tensor automatically

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

### CUDA Tensors
Tensors can be moved onto any device using the __.to__ method

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

Device configuration

In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)